// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIWMoKXIvZX62kpyfwc3wADKTKBSTa1XM',
    appId: '1:903959247239:web:3a52e11783c15f70043b22',
    messagingSenderId: '903959247239',
    projectId: 'tiktik-clone-4dbf3',
    authDomain: 'tiktik-clone-4dbf3.firebaseapp.com',
    storageBucket: 'tiktik-clone-4dbf3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf-vge0lWpuFuArkhb7ko4x9NxnCc_Dzo',
    appId: '1:903959247239:android:98a8b168f6d995cd043b22',
    messagingSenderId: '903959247239',
    projectId: 'tiktik-clone-4dbf3',
    storageBucket: 'tiktik-clone-4dbf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY_Yltbl8mmcQJI-L1od18g2BWCwUhaOg',
    appId: '1:903959247239:ios:7b332bc2c94a2c8a043b22',
    messagingSenderId: '903959247239',
    projectId: 'tiktik-clone-4dbf3',
    storageBucket: 'tiktik-clone-4dbf3.appspot.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY_Yltbl8mmcQJI-L1od18g2BWCwUhaOg',
    appId: '1:903959247239:ios:7a32258a3c81d755043b22',
    messagingSenderId: '903959247239',
    projectId: 'tiktik-clone-4dbf3',
    storageBucket: 'tiktik-clone-4dbf3.appspot.com',
    iosBundleId: 'com.example.tiktokClone.RunnerTests',
  );
}
